const STRINGS = {
  TRANSACTION_STATUS_CREATED: "created",
  TRANSACTION_STATUS_FAILED: "failed",
  TRANSACTION_STATUS_PAID: "paid",
  TRANSACTION_STATUS_EXPIRED: "expired",
  TRANSACTION_STATUS_DELIVERED: "delivered",
  TRANSACTION_STATUS_REVERTED: "reverted",
};

module.exports = STRINGS;
